In [4]:
import json

import pandas as pd

# https://huggingface.co/datasets/open-r1/OpenThoughts-114k-math

df = pd.read_parquet("filtered-correct-math-problems.parquet")
df

,source,problem,solution,messages,system,conversations,generated_token_count,correct
0,olympiads,There are 45 students in a certain exam in the...,\n1. **Identify the sets involved**:\n - Let...,[{'content': 'There are 45 students in a certa...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",715,True
1,olympiads,A wall clock takes 6 seconds to strike 3 times...,\nTo find the time it takes for the clock to c...,[{'content': 'A wall clock takes 6 seconds to ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",978,True
2,olympiads,"Like $2, 3, 5, 7$, a natural number greater th...","\n1. First, we start by calculating the expres...","[{'content': 'Like $2, 3, 5, 7$, a natural num...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",987,True
3,olympiads,The value of \(\frac{10+20+30+40}{10}\) is:\n(...,\nLet's solve the given expression step-by-ste...,[{'content': 'The value of \(\frac{10+20+30+40...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",997,True
4,olympiads,Vasiliy Petrov is working on an English langua...,\nTo determine the probability that Vasily Pet...,[{'content': 'Vasiliy Petrov is working on an ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",911,True
...,...,...,...,...,...,...,...,...
779,aops_forum,"**Q6.** At $3:00$ AM, the temperature was $...",1. Identify the initial temperature at 3:00 AM...,"[{'content': '**Q6.** At $3:00$ AM, the temp...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",966,True
780,aops_forum,"Which statement does not describe benzene, $\...",1. **Option (A):** Benzene is indeed an aromat...,[{'content': 'Which statement does not describ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",816,True
781,aops_forum,The critical temperature of water is the $ \te...,1. **Understanding the Critical Temperature:**...,[{'content': 'The critical temperature of wate...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",850,True
782,aops_forum,The value of which property decreases with an ...,1. **Analyzing Choice A (Viscosity):**\n - V...,[{'content': 'The value of which property decr...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",730,True
783,aops_forum,Consider a square of side length $12$ centim...,1. Calculate the perimeter of the original squ...,[{'content': 'Consider a square of side length...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",661,True

In [5]:
short_df = df[(df['generated_token_count'] < 1024) & (df['correct'])]
short_df

,source,problem,solution,messages,system,conversations,generated_token_count,correct
0,olympiads,There are 45 students in a certain exam in the...,\n1. **Identify the sets involved**:\n - Let...,[{'content': 'There are 45 students in a certa...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",715,True
1,olympiads,A wall clock takes 6 seconds to strike 3 times...,\nTo find the time it takes for the clock to c...,[{'content': 'A wall clock takes 6 seconds to ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",978,True
2,olympiads,"Like $2, 3, 5, 7$, a natural number greater th...","\n1. First, we start by calculating the expres...","[{'content': 'Like $2, 3, 5, 7$, a natural num...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",987,True
3,olympiads,The value of \(\frac{10+20+30+40}{10}\) is:\n(...,\nLet's solve the given expression step-by-ste...,[{'content': 'The value of \(\frac{10+20+30+40...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",997,True
4,olympiads,Vasiliy Petrov is working on an English langua...,\nTo determine the probability that Vasily Pet...,[{'content': 'Vasiliy Petrov is working on an ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",911,True
...,...,...,...,...,...,...,...,...
779,aops_forum,"**Q6.** At $3:00$ AM, the temperature was $...",1. Identify the initial temperature at 3:00 AM...,"[{'content': '**Q6.** At $3:00$ AM, the temp...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",966,True
780,aops_forum,"Which statement does not describe benzene, $\...",1. **Option (A):** Benzene is indeed an aromat...,[{'content': 'Which statement does not describ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",816,True
781,aops_forum,The critical temperature of water is the $ \te...,1. **Understanding the Critical Temperature:**...,[{'content': 'The critical temperature of wate...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",850,True
782,aops_forum,The value of which property decreases with an ...,1. **Analyzing Choice A (Viscosity):**\n - V...,[{'content': 'The value of which property decr...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",730,True
783,aops_forum,Consider a square of side length $12$ centim...,1. Calculate the perimeter of the original squ...,[{'content': 'Consider a square of side length...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",661,True

In [6]:
replacements = {
    "<|begin_of_thought|>": "<think>",
    "<|end_of_thought|>": "</think>",
    "<|begin_of_solution|>": "<answer>",
    "<|end_of_solution|>": "</answer>",
}

def multi_replace(text, mapping):
    for old, new in mapping.items():
        text = text.replace(old, new)
    return text

In [7]:
short_df["response"] = short_df["conversations"].apply(
    lambda arr: next((item["value"] for item in arr if item["from"] == "assistant"), None)
).apply(lambda x: multi_replace(x, replacements)).apply(lambda x: x.replace("</think>\n\n<answer>", "</think> <answer>"))

short_df

,source,problem,solution,messages,system,conversations,generated_token_count,correct,response
0,olympiads,There are 45 students in a certain exam in the...,\n1. **Identify the sets involved**:\n - Let...,[{'content': 'There are 45 students in a certa...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",715,True,"<think>\n\nOkay, let's try to figure out how m..."
1,olympiads,A wall clock takes 6 seconds to strike 3 times...,\nTo find the time it takes for the clock to c...,[{'content': 'A wall clock takes 6 seconds to ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",978,True,"<think>\n\nOkay, let's see. The problem is abo..."
2,olympiads,"Like $2, 3, 5, 7$, a natural number greater th...","\n1. First, we start by calculating the expres...","[{'content': 'Like $2, 3, 5, 7$, a natural num...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",987,True,"<think>\n\nOkay, let me try to figure out how ..."
3,olympiads,The value of \(\frac{10+20+30+40}{10}\) is:\n(...,\nLet's solve the given expression step-by-ste...,[{'content': 'The value of \(\frac{10+20+30+40...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",997,True,"<think>\n\nOkay, let's see. The question is as..."
4,olympiads,Vasiliy Petrov is working on an English langua...,\nTo determine the probability that Vasily Pet...,[{'content': 'Vasiliy Petrov is working on an ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",911,True,"<think>\n\nOkay, so Vasiliy has to match 10 En..."
...,...,...,...,...,...,...,...,...,...
779,aops_forum,"**Q6.** At $3:00$ AM, the temperature was $...",1. Identify the initial temperature at 3:00 AM...,"[{'content': '**Q6.** At $3:00$ AM, the temp...",Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",966,True,"<think>\n\nOkay, let's try to figure out this ..."
780,aops_forum,"Which statement does not describe benzene, $\...",1. **Option (A):** Benzene is indeed an aromat...,[{'content': 'Which statement does not describ...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",816,True,"<think>\n\nOkay, let's see. The question is as..."
781,aops_forum,The critical temperature of water is the $ \te...,1. **Understanding the Critical Temperature:**...,[{'content': 'The critical temperature of wate...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",850,True,"<think>\n\nOkay, so I need to figure out which..."
782,aops_forum,The value of which property decreases with an ...,1. **Analyzing Choice A (Viscosity):**\n - V...,[{'content': 'The value of which property decr...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",730,True,"<think>\n\nOkay, let's try to figure out this ..."
783,aops_forum,Consider a square of side length $12$ centim...,1. Calculate the perimeter of the original squ...,[{'content': 'Consider a square of side length...,Your role as an assistant involves thoroughly ...,"[{'from': 'user', 'value': 'Return your final ...",661,True,"<think>\n\nOkay, let's tackle this problem ste..."

In [8]:
short_df.rename(columns={'problem': 'prompt'}, inplace=True)

In [9]:
short_df = short_df[['prompt', 'response']]
short_df

,prompt,response
0,There are 45 students in a certain exam in the...,"<think>\n\nOkay, let's try to figure out how m..."
1,A wall clock takes 6 seconds to strike 3 times...,"<think>\n\nOkay, let's see. The problem is abo..."
2,"Like $2, 3, 5, 7$, a natural number greater th...","<think>\n\nOkay, let me try to figure out how ..."
3,The value of \(\frac{10+20+30+40}{10}\) is:\n(...,"<think>\n\nOkay, let's see. The question is as..."
4,Vasiliy Petrov is working on an English langua...,"<think>\n\nOkay, so Vasiliy has to match 10 En..."
...,...,...
779,"**Q6.** At $3:00$ AM, the temperature was $...","<think>\n\nOkay, let's try to figure out this ..."
780,"Which statement does not describe benzene, $\...","<think>\n\nOkay, let's see. The question is as..."
781,The critical temperature of water is the $ \te...,"<think>\n\nOkay, so I need to figure out which..."
782,The value of which property decreases with an ...,"<think>\n\nOkay, let's try to figure out this ..."
783,Consider a square of side length $12$ centim...,"<think>\n\nOkay, let's tackle this problem ste..."

In [10]:
short_df.to_parquet('short_reasoning_784.parquet', index=False)